# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/wearefair/gurl
    steps:
      - checkout
      - restore_cache:
          keys:
              - vendor-dir-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install deps
          command: dep ensure -v
      - run:
          name: Run tests
          command: go test -v -race ./...
      - run:
          name: Verify binary can build
          command: go build -v
